name: Run API Request Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # This runs the job at the start of every hour
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run-api-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # You can specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install any other dependencies if needed

      - name: Run API Request Script
        run: python api_request.py
